
[sources.api_server]
type = "stdin"

# [sinks.console]
# inputs = ["llamaedge_api_server"]
# target = "stdout"
# type = "console"
# encoding.codec = "json"

[sinks.log_file]
type = "file"
inputs = ["api_server"]
path = "log/gaianet-api-server.log"
encoding.codec = "json"

# [sinks.aws_s3]
# type = "aws_s3"
# inputs = [ "llamaedge_api_server" ]
# bucket = "my-bucket"
